### ISSUE TITLE
Update to support Qt 5.7.0?

### ISSUE THREAD

**Issue by cpace6** [osechet/conan-qt#10]
Hi osechet, what is the best way we could update this to use Qt 5.7.0? Should I fork this, or make a 5.7.0/testing branch?

**Comment by osechet** [comment]
The best way would be to create a 5.7.0/testing branch in a PR. As soon as your PR will be accepted, continuous integration will automatically generate the packages.

**Comment by cpace6** [comment]
Thanks, I submitted a PR

**Comment by cpace6** [comment]
Hi osechet, 
After merging the PR for 5.7.0/testing, the only binaries available on conan.io are Linux/x86_64/gcc 4.8 Release and Debug. I was able to build the package from source successfully on my machine for Windows, but it took about an hour. Could we get the packages for Windows/x86_64/VS2014 Release and Debug generated and posted? gcc 5.4 Release and Debug packages would be helpful as well. 
Thanks,
Chris
