### ISSUE TITLE
Problem with 5.6.0 in Win

### ISSUE THREAD

**Issue by memsharded** [osechet/conan-qt#2]
I have been able to "almost" compile it in Win, but it finish with one error, reported here: https://bugreports.qt.io/browse/QTBUG-51847

It seems to be fixed in 5.6.1, are you ok about creating a package for 5.6.1 instead? If so, I will try and include the version bump in my next PR.

**Comment by osechet** [comment]
It seems the bug only affects latest versions of MSVC (2013 and 2015). With my latest commit I have been able to make it work on Windows (win 7) with MSVC 2012 (using the short_paths.conf trick).
Qt 5.6.0 being an LTS, it would be nice to have a working package for that version, even if it's limited to msvc 2010 and 2012. 
If you are really blocked, you could do your modifications in a new branch. What do you think?

**Comment by memsharded** [comment]
Well, it seems that the adoption of MSVC 2015 is very large, the largest MSVC by far, so it would be important to provide the best support for it. 
Furthermore, Qt follows semver, and 5.6.1 is just a patch for 5.6.0, so it is also a LTS version, but with some bug fixes. It should work with previous 2010 and 2012 versions, besides 2015, of course. Check https://blog.qt.io/blog/2015/12/18/introducing-long-term-support/  I would say it is not worth packaging both versions, that is why I was asking you. I am building 5.6.1 right now in Win, I will let you know.

**Comment by osechet** [comment]
Fine. Since I don't have a lot of time for this project right now, I'll follow your position, as long as the package is compatible with at least msvc 2012 (it's a constraint for my current project).

**Comment by osechet** [comment]
Problems on Windows with Visual Studio are fixed by PR #3.
