### ISSUE TITLE
Visual Studio debug runtime library

### ISSUE THREAD

**Issue by rdeterre** [osechet/conan-qt#24]
Hi,

Looking at the binary packages on Bintray for your Qt package, it looks like the debug builds for Visual Studio use the MD runtime, which is a release mode. Is this expected, or should the build be made with MDd instead?

I am trying to pass `pure_c=False` to `add_common_builds` in `build.py` to see if this will change the runtime used, but I'm very inexperienced with the conan package tools so I may be completely off.

Thanks,

Romain

**Comment by osechet** [comment]
@rdeterre I'm a little bit surprise. The CI process normally builds 4 packages for MSVC: Debug/MDd, Release/MD, Debug/MTd and Release/MT. Which repo are you using? Which version of Qt?

**Comment by rdeterre** [comment]
Thanks very much for your answer. The "MD" builds were found on conan.io and conan-transit on Bintray. For example, the query `conan search Qt/5.8.0@osechet/stable -r conan-transit -q "os=Windows AND build_type=Debug"` yields two packages (with IDs `25a2...` and `5bf7...`) that are listed as using "MD" runtime.

I'll copy the `conan.conf` file from the machine where I had the issues here tomorrow.

**Comment by osechet** [comment]
Yes, you are right: it seems something went wrong during the package creation process. However I won't be able to do anything in conan-transit since it's just a read-only repo.
I'm working on an update of the package that is available here: https://bintray.com/osechet/Conan.
But the `5.8.0/stable` has not been uploaded yet. You can maybe try with the `5.8.0/testing`. Here is how:
- Add the repo to your registry:
```
conan remote add conan-osechet https://api.bintray.com/conan/osechet/Conan
```
- Install the manifest for the Qt/5.8.0@osechet/testing reference:
```
conan install Qt/5.8.0@osechet/testing --build=never
```
- Force conan to use the new repo for this reference:
```
conan remote update_ref Qt/5.8.0@osechet/testing conan-osechet
```
- Update the dependency in your project's conanfile
- Run `conan install...` in your project's build dir

**Comment by rdeterre** [comment]
I followed these steps, and got to a `registry.txt` file that looks like this:

```
conan-transit https://conan-transit.bintray.com True
conan-center https://conan.bintray.com True
conan-osechet https://api.bintray.com/conan/osechet/Conan True
local http://localhost:9300 True
...

Qt/5.8.0@osechet/testing conan-osechet
...
```

Now, if I try `conan install` in a test repository like this : `conan install .. -s build_type=Release -s compiler="Visual Studio" -s compiler.runtime="MD"`, everything works well. However, if I run it with debug options, I get an error:

```
C:\Users\rdeterre\Documents\test-repo\build>conan install .. -s build_type=Debug -s compiler="Visual Studio" -s compiler.runtime="MDd"
Requirements
    Boost/1.60.0@lasote/stable from local
    Qt/5.8.0@osechet/testing from conan-osechet
    gsl/0.0.1@KindDragon/stable from local
    zlib/1.2.8@lasote/stable from local
Packages
    Boost/1.60.0@lasote/stable:b17b520b4b55729a7391c6b2d20631fec4cf1564
    Qt/5.8.0@osechet/testing:cfa1e2891787224833b381693bd982f1f906e023
    gsl/0.0.1@KindDragon/stable:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9
    zlib/1.2.8@lasote/stable:c32596dcd26b8c708dc3d19cb73738d2b48f12a8

WARN: Can't find a 'Qt/5.8.0@osechet/testing' package for the specified options and settings:
- Settings: arch=x86_64, build_type=Debug, compiler=Visual Studio, compiler.runtime=MDd, compiler.version=14, os=Windows
- Options: canvas3d=False, gamepad=False, graphicaleffects=False, imageformats=False, location=False, opengl=desktop, serialport=False, shared=True, svg=False, tools=False, webengine=False, websockets=False, xmlpatterns=False

ERROR: Missing prebuilt package for 'Qt/5.8.0@osechet/testing'
Try to build it from sources with "--build Qt"
Or read "http://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package"
```

I tried listing the binary packages on your Bintray remote, but there seems to be some authentication failure:

```
C:\Users\rdeterre\Documents\test-repo\build>conan search Qt/5.8.0@osechet/testing -r conan-osechet
ERROR: Permission denied for user: 'rdeterre'. [Remote: conan-osechet]
```

Note that just listing the packages on the remote works (i.e. `conan search -r conan-osechet`)

**Comment by osechet** [comment]
The requested package is there. If I run the `conan search` command on my machine, I get:
```
Package_ID: cfa1e2891787224833b381693bd982f1f906e023
        [options]
            canvas3d: False
            gamepad: False
            graphicaleffects: False
            imageformats: False
            location: False
            opengl: desktop
            serialport: False
            shared: True
            svg: False
            tools: False
            webengine: False
            websockets: False
            xmlpatterns: False
        [settings]
            arch: x86_64
            build_type: Debug
            compiler: Visual Studio
            compiler.runtime: MDd
            compiler.version: 14
            os: Windows
        outdated from recipe: False
```
There was an issue with my bintray account until today. It's maybe the reason why you couldn't get it. Can you try again?

**Comment by rdeterre** [comment]
I just tried again and everything works now. Thanks very much for your help!
