### ISSUE TITLE
No more strawberryperl due to no dependence on perl

### ISSUE THREAD

**Issue by vadixidav** [osechet/conan-qt#38]
[This](101ebe6330d8d836bee2052d71c904e61bb7e3b8) commit says it removed the perl dependency. Is there still a need to require strawberryperl anymore then?

**Comment by vadixidav** [comment]
It seems QT's configure requires perl. Closing.

**Comment by ericLemanissier** [comment]
actually, configure does not require perl if --no-syncqt is provided. I will do some tests

**Comment by ericLemanissier** [comment]
Ok, perl is not needed if we download submodules as archive, not git, so it will not be needed when https://github.com/osechet/conan-qt/pull/35 is merged
