### ISSUE TITLE
Windows packages

### ISSUE THREAD

**Issue by tim-lebedkov** [osechet/conan-qt#7]
Hello,

what is the current status of the Qt package for Windows? Are there any uncommitted changes? Does anybody still work on this? Why is the master branch not updated and "testing" is still used? When can I expect Windows Qt packages? Do you need any help?

**Comment by osechet** [comment]
Hello,
The Qt package is still work in progress. However, there is already a working version on Windows, as long as you use Visual Studio. You can work with it using the [testing branch](https://www.conan.io/source/Qt/5.6.1-1/osechet/testing). If you do so, you may have get the #6 issue. In this case you have to create a `qt.conf` file in the same directory as your executable with the following content:
```
[Paths]
Prefix = /path/to/the/conan/qt/package
```

**Comment by tim-lebedkov** [comment]
I use MinGW-w64. When can I expect Windows Qt packages? Do you need any help?

**Comment by osechet** [comment]
@tim-lebedkov I spent some time on building Qt on Windows with Mingw this weekend but I get compilation problems for which I cannot find any reference on Internet. I'm using msys2 and I followed the option B instructions from [here](https://wiki.qt.io/MinGW-64-bit#MinGW-builds_.28with_OpenSSL.2C_ICU_and_QtWebKit.29). I will try again during the week following the option A.

**Comment by tim-lebedkov** [comment]
Any news? Can I help somehow?

**Comment by osechet** [comment]
@tim-lebedkov Sorry for not answering earlier. I ran into a lot of issues trying to build Qt on Windows with Mingw. I tried to follow the 2 options from Qt wiki but none worked.
If you want to help, you could try to build Qt 5.6.1 with Mingw and tell me if it works for you. Then I could try to follow your steps to do it on my machine.

**Comment by osechet** [comment]
@tim-lebedkov I have finally been able to build with MinGW and I updated the conan package. Since Qt is (very) long to build, is there a version of gcc you would like to have to test?

**Comment by tim-lebedkov** [comment]
The following 2 would be the most interesting for me:

1.  -s compiler.version="4.9"   -s compiler.exception="sjlj"   -s arch="x86"   -s compiler.threads="posix"   -s os="Windows"   -s build_type="Release"   -s compiler="gcc"

2.
  -s compiler.version="4.9"   -s compiler.exception="seh"   -s arch="x86_64"   -s compiler.threads="posix"   -s os="Windows"   -s build_type="Release"   -s compiler="gcc"

**Comment by osechet** [comment]
@tim-lebedkov Building the full Qt being very long, I created a new package including only the qtbase modules (Core, Gui, network, ...). If you are not using very specific Qt modules, it may work for you. The new package is available [here](https://github.com/osechet/conan-qt-base).
You can find the pre-compiled versions on [conan.io](https://www.conan.io/source/QtBase/5.6.1-1/osechet/testing).
Your feeback is welcomed.

**Comment by osechet** [comment]
The package now builds with MSVC and mingw.
