### ISSUE TITLE
fails on osx

### ISSUE THREAD

**Issue by yandreiy** [osechet/conan-qt#8]
Tested this on osx, and the build fails:

make[5]: Nothing to be done for `first'.
make[2]: **\* [sub-widgets-make_first] Error 2
make[1]: **\* [sub-examples-make_first] Error 2
make: **\* [module-qtbase-make_first] Error 2

Qt/5.6.1-1@osechet/testing: ERROR: Package '0b89d7271c641c0ed63cb474727fe5887401d9c0' build failed
Qt/5.6.1-1@osechet/testing: WARN: Build folder .../.conan/data/Qt/5.6.1-1/osechet/testing/build/0b89d7271c641c0ed63cb474727fe5887401d9c0
ERROR: Qt: Error 512 while executing cd qt-everywhere-opensource-src-5.6.1 && make -j 4

**Comment by osechet** [comment]
Not surprising. It has never been tested on osx since I don't have a platform to test.

**Comment by osechet** [comment]
@yandreiy Could you try the new Qt package I created. It only includes the qtbase modules (Core, Gui, Network...). If you don't need any of the extra Qt package, it should work. The new package is available [here](https://www.conan.io/source/QtBase/5.6.1-1/osechet/testing). There is still no pre-compiled package for MacOs but now you should be able to build it from source.
