### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by ForNeVeR** [osechet/conan-qt#9]
While running `conan install --build Qt`, I wasn't able to build the project. Here're the latest lines from the build log: https://gist.github.com/ForNeVeR/63731ba2d257000319944b58a7570d78

I'm using the following `conanfile.txt`:

```
[requires]
icu/57.1@vitallium/stable
Qt/5.6.1-1@osechet/testing

[generators]
cmake
```

and the following `conaninfo.txt`:

```
[settings]
    arch=x86
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    os=Windows

[requires]
    Boost/1.Y.Z

[options]


[full_settings]
    arch=x86
    build_type=Release
    compiler=Visual Studio
    compiler.runtime=MD
    compiler.version=14
    os=Windows

[full_requires]
    Boost/1.60.0@lasote/stable:ee5dab950b6ea94ae953b93c55343e98c2ec39df
    zlib/1.2.8@lasote/stable:63da998e3642b50bee33f4449826b2d623661505

[full_options]
    Boost:header_only=False
    Boost:python=False
    Boost:shared=False
    zlib:shared=False

[scope]
    dev=True
```

I have Visual Studio 2015 Update 3 installed with all the required C++ stuff (I believe). Tried to change `arch=x86` to `arch=x86_64` both in the `[options]` and `[full_options]`, and it didn't helped.

**Comment by ForNeVeR** [comment]
Probably I've messed up the runtime settings (`MT` vs `MDd` etc).

**Comment by osechet** [comment]
Can I suggest to use my other Qt package: https://github.com/osechet/conan-qt-base?
It only includes the base modules (cover most of the cases) and is much faster to build.

**Comment by ForNeVeR** [comment]
Yep, thanks, I will try.

**Comment by osechet** [comment]
Windows build is now working.
